### ISSUE TITLE
Linking Errors using this 

### ISSUE THREAD

**Issue by vivekvrao** [Microsoft/hiredis#1]
First of all, thanks for taking on this project. Redis client support on windows is sorely needed - and I've been waiting for this project to come about. So keep up the good work.

Dont know if this project is ready yet. If not - please let me know. I'll wait.

I tried to link this with my project - and gives me linking errors. 

Error	LNK1120	29 unresolved externals	
Error	LNK2019	unresolved external symbol "int __cdecl crtget_osfhandle(int)" (?crtget_osfhandle@@YAHH@Z) referenced in function __catch$?redis_write_impl@@YAHHPBXI@Z$1	..\hiredis.lib(Win32_FDAPI.obj)	

and 28 more.

I tried to switch the hiredis project to a Executable and added a main (to check that I didnt set up incorrectly) . That also gives the same linking errors.
thanks,

**Comment by enricogior** [comment]
Hi @vivekvrao 
the project is on going, we haven't released an official build yet, but the code is up there for playing with it and providing feedback.
Thank you.
