### ISSUE TITLE
subscribe doesn't work. using ae callback never gets invoked.

### ISSUE THREAD

**Issue by vivekvrao** [Microsoft/hiredis#2]
subscribe doesn't work. Callback never gets invoked.

In the win32_example project - I edited example-ae-win.c 
replaced the test logic with - the following
``
redisAsyncCommand(c, getCallbackContinue, "0", "subscribe foo ");

aeMain(loop);
``
then publishing from redis-cli > publish foo bar

no callback is received. am I missing something?

**Comment by enricogior** [comment]
Hi @vivekvrao 
I'll look into it and I'll let you know, presumably tomorrow.
Thank you.

**Comment by enricogior** [comment]
@vivekvrao 
I've found the bug and I'll release the fix as soon as possible.
Thank you for reporting the issue.

**Comment by vivekvrao** [comment]
thanks, that works great. brought out a different bug in set/publish in async mode. Will open a separate issue with that. thanks.
